backend:
  name: github
  repo: hadjismaelbolaly/MaraboutAmour
  branch: main
  base_url: https://marabout-amour.vercel.app
  auth_endpoint: api/auth

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Articles de blog"
    label_singular: "Article"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    identifier_field: title
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Résumé (affiché dans la liste des articles)", name: "excerpt", widget: "text" }
      - { label: "Photo de couverture", name: "image", widget: "image", required: false }
      - { label: "Contenu de l'article", name: "body", widget: "markdown" }
